### ISSUE TITLE
Issue with scope in a for loop

### ISSUE THREAD

**Issue by mlabita37** [mlabita37/Game-Game#1]
Issue with scope in a for loop

**Comment by amadden80** [comment]
in person

**Comment by mlabita37** [comment]
Having some trouble with this same 'for' loop. I can't seem to grab the value of the 'class' I'm targeting. Here is my code:

ShipStrikeGame.prototype.playerMove = function(computerLocations) {
var scope = this;
$('.computerCell').on('click', function(){
  $compCell = $(this);
  $compCell = $compCell.val('value');
  for(var i=0; i < computerLocations.length; i++){
    if($compCell === computerLocations[i][i]) {
      $compCell.css({'background-color':'red'});
      $compCell.text('HIT');
      $compCell.attr('id','hit');
    }else {
      $compCell.css({'background-color':'blue'});
      $compCell.text('MISS');
      $compCell.attr('id', 'miss');
    }
  }
})
};
computerLocations is my array of randomly generated locations for the computer's ships. I'm trying to see whether or not each computer location matches the value of the cell that has been clicked. I've tried using $compCell.val('value') in order to get the value associated with that tag. I think the only issue is that I'm not grabbing the value correctly. Right now, the functionality works, but it does not follow the rules of my 'if/else' statement.

**Comment by clay-reed-a** [comment]
Hey Michael, 

This is looking mighty impressive. 

I see two things here I have questions about. 
1. 

Why are you indexing into `computerLocations` twice? And why is the second "indexing" using the same value as the first? 

Right now what this loop would do is go...

 `computerLocations[0][0]`
 `computerLocations[1][1]`
 `computerLocations[2][2]`
 `computerLocations[3][3]`
 `computerLocations[4][4]`

This basically means it's moving diagonally across some kinda matrix:

```
// And what is a Matrix?
[[[0, 0], [0, 1], [0, 2], [0, 3], [0, 4]], 
 [[1, 0], [1, 1], [1, 2], [1, 3], [1,4]], 
 [[2, 0], [2, 1], [2, 2], [2, 3], [2, 4]], 
 [[3, 0], [3, 1], [3, 2], [3, 3], [3, 4]], 
 [[4, 0], [4, 1], [4, 2], [4, 3], [4, 4]]]
// Oh, OK. I guess that's what a Matrix is. 
```

Is that what you intend? 
1. 

What does [the jQuery `val` method](http://api.jquery.com/val/) do? 

`$compCell.val('value')` 

It would look to me like this wouldn't get the value of [an attribute](https://en.wikipedia.org/wiki/HTML_attribute) but the value of, like, an input tag, right? 

And if you pass it a value... What happens? 

Try it out in [the Chrome console](https://developer.chrome.com/devtools/docs/console) after reading about it!
